name: 'The name of your action here'
description: 'Provide a description here'
author: 'Your name or organization here'

# Define your inputs here.
inputs:
  github_token:
    required: true
  jpegQuality:
    description: 'Quality of JPEG images'
    required: false
    default: 80
  jpegProgressive:
    description: 'Quality of JPEG images'
    required: false
    default: 80
  pngQuality:
    description: 'Quality of PNG images'
    required: false
    default: 80
  webpQuality:
    description: 'Quality of WEBP images'
    required: false
    default: 80
  compressOnly:
    description: 'Only compress images'
    required: false
    default: true

# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
